apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: cert-manager-issuers
  namespace: cert-manager
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "15m"
spec:
  type: Static
  defaultValues:
    email: ringo@hardes.be