---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chartRef:
    kind: OCIRepository
    name: cilium
  interval: 1h
  values:
    cgroup:
      automount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    cleanState: false
    cleanBpfState: false
    gatewayAPI:
      enabled: true
    hubble:
      #  https://docs.cilium.io/en/stable/gettingstarted/hubble_setup/
      relay:
        enabled: false
      ui:
        enabled: false
    #  https://docs.cilium.io/en/stable/network/servicemesh/ingress/
    ingressController:
      enabled: false
    ipam:
      mode: kubernetes
    ipv4:
      enabled: true
    ipv6:
      enabled: false
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 7445
    kubeProxyReplacement: true
    # https://docs.cilium.io/en/stable/network/l2-announcements/
    l2announcements:
      enabled: true
    rollOutCiliumPods: true
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
