apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: &app flux-operator-route
  namespace: &ns flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  dependsOn:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      name: services
      namespace: kube-system
      ready: true
  resources:
    - apiVersion: cilium.io/v2
      kind: CiliumNetworkPolicy
      metadata:
        name: allow-gateway-to-flux-operator-web
        namespace: flux-system
      spec:
        endpointSelector:
          matchLabels:
            app.kubernetes.io/instance: flux-operator
            app.kubernetes.io/name: flux-operator
        ingress:
          - fromEntities:
              - ingress
              - host
              - remote-node
            toPorts:
              - ports:
                  - port: "9080"
                    protocol: TCP
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: *app
        namespace: *ns
      spec:
        hostnames:
          - flux.${cluster_domain}
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: services
            namespace: kube-system
            sectionName: http
        rules:
          - backendRefs:
              - group: ""
                kind: Service
                name: flux-operator
                port: 9080
                weight: 1
