apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: cert-manager-issuers
  namespace: cert-manager
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "15m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  dependsOn:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: scaleway-certmanager-webhook
      namespace: cert-manager
      ready: true
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: cert-manager-issuers
  resources:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: scaleway-issuer-${cluster_name}
      spec:
        acme:
          email: << inputs.email >>
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: certmanager-scaleway-private-key-${cluster_name}
          solvers:
            - selector:
                dnsZones:
                  - ${cluster_domain}
              dns01:
                webhook:
                  groupName: acme.scaleway.com
                  solverName: scaleway
