apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: &app trust-manager
  namespace: &ns cert-manager
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "15m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: cert-manager
      namespace: *ns
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: *app
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: *app
        namespace: *ns
      spec:
        ref:
          tag: << inputs.tag >>
        interval: 15m
        layerSelector:
          mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
          operation: copy
        url: oci://quay.io/jetstack/charts/trust-manager
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: *app
        namespace: *ns
      spec:
        chartRef:
          kind: OCIRepository
          name: *app
        interval: 1h
        values:
          crds:
            enabled: true
