# https://longhorn.io/docs/1.12.1/advanced-resources/os-distro-specific/talos-linux-support/
# https://docs.siderolabs.com/kubernetes-guides/csi/longhorn
apiVersion: v1alpha1
kind: RawVolumeConfig
name: longhorn
provisioning:
  diskSelector:
    match: disk.transport == 'nvme' && !system_disk
  minSize: 1TiB