apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: onepassword-sdk-hardes
  namespace: external-secrets
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "5m"
spec:
  type: Static
  defaultValues:
    vault: homelab-desk8s
