apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: &app podinfo
  namespace: &ns default
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: *app
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: *app
        namespace: *ns
      spec:
        ref:
          tag: << inputs.tag >>
        interval: 15m
        layerSelector:
          mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
          operation: copy
        url: oci://ghcr.io/stefanprodan/charts/podinfo
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: *app
        namespace: *ns
      spec:
        chartRef:
          kind: OCIRepository
          name: *app
        interval: 1h
        values:
          replicaCount: 2
          httpRoute:
            enabled: true
            parentRefs:
              - name: apps
                namespace: kube-system
                sectionName: http
            hostnames:
              - podinfo.${cluster_domain}
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: *app
        namespace: *ns
      spec:
        # Secret names are always required.
        secretName: podinfo-hardes-tls

        duration: 504h # 21d
        renewBefore: 168h # 7d

        subject:
          organizations:
            - cert-manager

        # At least one of commonName (possibly through literalSubject), dnsNames, uris, emailAddresses, ipAddresses or otherNames is required.
        dnsNames:
          - podinfo.${cluster_domain}

        # Issuer references are always required.
        issuerRef:
          name: scaleway-issuer-${cluster_name}
          # We can reference ClusterIssuers by changing the kind here.
          # The default value is Issuer (i.e. a locally namespaced Issuer)
          kind: ClusterIssuer
