apiVersion: v1alpha1
kind: LinkConfig
name: ethernet
up: true
mtu: 1500 # The interface's MTU.
addresses:
  - address: 172.16.35.6/24
routes:
  - gateway: 172.16.35.1 # The route's gateway (if empty, creates link scope route).
    metric: 1024 # The optional metric for the route.
