---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scaleway-certmanager-webhook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-hardes
  target:
    name: scaleway-certmanager-webhook
    template:
      data:
        SCW_ACCESS_KEY: "{{ .accessKey }}"
        SCW_SECRET_KEY: "{{ .secretKey }}"
  dataFrom:
    - extract:
        key: scaleway-certmanager-webhook