---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scaleway-certmanager-webhook
spec:
  chartRef:
    kind: OCIRepository
    name: scaleway-certmanager-webhook
  interval: 1h
  values:
    secret:
      externalSecretName: scaleway-certmanager-webhook
