apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: unifi-dns
  namespace: network
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "15m"
spec:
  type: Static
  defaultValues:
    externalDns:
      tag: 1.21.1
    unifiWebhook:
      tag: 0.10.12
