---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/external-secrets/onepassword-sdk-hardes/app

patches:
  - target:
      group: external-secrets.io
      version: v1
      kind: ClusterSecretStore
      name: onepassword-sdk-hardes
    path: onepassword-sdk-hardes-vault.yaml
