apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: tuppr-upgrade
  namespace: system-upgrade
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "15m"
spec:
  type: Static
  defaultValues:
    kubernetes:
      tag: v1.37.0
    talos:
      tag: v1.13.9
