apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: &app longhorn-storage-classes
  namespace: &ns longhorn-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "15m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: longhorn
      namespace: *ns
      ready: true
  resources:
    - kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: longhorn-local
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      parameters:
        backupTargetName: "default"
        dataEngine: "v1"
        numberOfReplicas: "1"
        fromBackup: ""
        fsType: "xfs"
