apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: &app pocket-id-identities
  namespace: &ns security
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "15m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      # Needs a deployed `pocket-id` cluster
      name: pocket-id-instance
      namespace: *ns
  resources:
    - apiVersion: pocketid.internal/v1alpha1
      kind: PocketIDUser
      metadata:
        name: pocket-id-user-ringo
        namespace: *ns
      spec:
        admin: true
        displayName:
          value: "Ringo De Smet"
        email:
          value: "ringo@de-smet.name"
        firstName:
          value: Ringo
        lastName:
          value: "De Smet"
        username:
          value: ringods
