---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/system-upgrade/tuppr/app

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: tuppr
    path: tuppr-helm-release.yaml
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: OCIRepository
      name: tuppr
    path: tuppr-oci-repository.yaml
