apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: &app zitadel-db
  namespace: &ns security
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "15m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  dependsOn:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      # Needs External Secrets operator deployed before deploying a `Password` & `ExternalSecret` resource
      name: external-secrets
      namespace: external-secrets
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      # Needs cloudnative-pg operator deployed before issuing a `Cluster` resource
      name: cloudnative-pg
      namespace: cnpg-system
    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      # Needs the deployed `StorageClass` resource named `longhorn-local`
      name: longhorn-local
  resources:
    - apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      metadata:
        name: *app
        namespace: *ns
      spec:
        length: 16
        digits: 5
        symbols: 5
        symbolCharacters: "-_$@%"
        noUpper: false
        allowRepeat: true
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: zitadel-db-secret
        namespace: *ns
      spec:
        target:
          name: zitadel-db-secret
          template:
            data:
              username: "zitadel"
              password: "{{ .password }}"
        dataFrom:
          - sourceRef:
              generatorRef:
                apiVersion: generators.external-secrets.io/v1alpha1
                kind: Password
                name: *app
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: *app
        namespace: *ns
      spec:
        instances: 3
        bootstrap:
          initdb:
            database: zitadel
            owner: zitadel
            secret:
              name: zitadel-db-secret
        storage:
          storageClass: longhorn-local
          size: 3Gi
