apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: &app onepassword-sdk-hardes
  namespace: &ns external-secrets
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: external-secrets
      namespace: *ns
      ready: true
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: *app
  resources:
    - apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      metadata:
        name: onepassword-sdk-hardes
      spec:
        provider:
          onepasswordSDK:
            auth:
              serviceAccountSecretRef:
                name: onepassword-sdk-hardes-secret
                namespace: external-secrets
                key: token
            vault: << inputs.vault >>
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: onepassword-sdk-hardes
      spec:
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword-sdk-hardes
        target:
          name: onepassword-sdk-hardes-secret
        data:
          - secretKey: token
            remoteRef:
              key: 1password-svc/credential