apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: unifi-dns
  namespace: network
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: unifi-dns
  resources:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: unifi-dns
        namespace: &ns network
      spec:
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword-sdk-hardes
        target:
          name: &secret unifi-api-key
          template:
            data:
              UNIFI_API_KEY: "{{ .unifiApiKey }}"
        dataFrom:
          - extract:
              key: external-dns-unifi
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: unifi-dns
        namespace: *ns
      spec:
        ref:
          tag: << inputs.externalDns.tag >>
        interval: 15m
        layerSelector:
          mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
          operation: copy
        url: oci://ghcr.io/home-operations/charts-mirror/external-dns
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: &app unifi-dns
        namespace: *ns
      spec:
        chartRef:
          kind: OCIRepository
          name: unifi-dns
        interval: 1h
        values:
          enableGatewayListenerSets: true
          fullnameOverride: *app
          provider:
            name: webhook
            webhook:
              image:
                repository: ghcr.io/home-operations/external-dns-unifi-webhook
                tag: << inputs.unifiWebhook.tag >>
              env:
                - name: UNIFI_HOST
                  value: https://172.16.10.1
                - name: UNIFI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: *secret
                      key: UNIFI_API_KEY
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: http-webhook
                initialDelaySeconds: 10
                timeoutSeconds: 5
              readinessProbe:
                httpGet:
                  path: /readyz
                  port: http-webhook
                initialDelaySeconds: 10
                timeoutSeconds: 5
          triggerLoopOnEvent: true
          policy: sync
          sources:
            - gateway-httproute
            - service
          txtOwnerId: << inputs.cluster >>
          txtPrefix: k8s.<< inputs.cluster >>.%{record_type}-
          domainFilters:
            - << inputs.domain >>
#          serviceMonitor:
#            enabled: true
          podAnnotations:
            secret.reloader.stakater.com/reload: *secret