apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: &app headlamp-oauth
  namespace: &ns kube-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "15m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      # Needs the deployed Pocket-ID identities
      name: pocket-id-identities
      namespace: security
  resources:
    - apiVersion: pocketid.internal/v1alpha1
      kind: PocketIDUserGroup
      metadata:
        name: headlamp-users
        namespace: *ns
      spec:
        friendlyName: "Headlamp Users"
        users:
          userRefs:
            - name: pocket-id-user-ringo
              namespace: security
    - apiVersion: pocketid.internal/v1alpha1
      kind: PocketIDOIDCClient
      metadata:
        name: headlamp-app
        namespace: *ns
      spec:
        name: Headlamp
        launchUrl: https://headlamp.${cluster_domain}
        callbackUrls:
          - https://headlamp.${cluster_domain}/oidc-callback
        allowedUserGroups:
          - name: headlamp-users
        pkceEnabled: true
        isPublic: true
        secret:
          name: headlamp-oidc
          keys:
            clientID: OIDC_CLIENT_ID
            clientSecret: OIDC_CLIENT_SECRET
            issuerUrl: OIDC_ISSUER_URL
            callbackUrls: OIDC_CALLBACK_URL
