apiVersion: v1alpha1
kind: LinkAliasConfig
name: ethernet # Alias for the link.
# Selector to match the link to alias.
selector:
  match: glob("0c:c4:7a:32:31:64", mac(link.permanent_addr)) # The Common Expression Language (CEL) expression to match the link.