---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-sdk-hardes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-hardes
  target:
    name: onepassword-sdk-hardes-secret
  data:
    - secretKey: token
      remoteRef:
        key: 1password-svc/credential